os: osx
osx_image: xcode11.5
language: swift
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 8

script:
- xcodebuild -project SwiftUICalculator.xcodeproj -scheme SwiftUICalculator -destination "platform=iOS Simulator,name=iPhone 8" -sdk iphonesimulator13.5 CODE_SIGNING_REQUIRED=NO
